name: Build Unity Project

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
        
      - name: Cache Unity Library
        uses: actions/cache@v2
        id: cache-unity
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64 
          unityVersion: 2022.3.19f1
          
      - uses: actions/upload-artifact@v3 
        with:
          name: Build-StandaloneWindows64 
          path: build/StandaloneWindows64
          continue-on-error: true
      
      - name: Retry on failure and delete old artifacts
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            const res = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

            res.data.artifacts
              .forEach(({ id }) => {
                github.rest.actions.deleteArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: id,
                })
              })
              
      - name: Retry artifact upload
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3 
        with:
          name: Build-StandaloneWindows64 
          path: build/StandaloneWindows64
          continue-on-error: true
