name: Format check on push

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1

      - name: Cache NuGet packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
        
      - name: Restore dependencies
        run: dotnet restore "./Thesis.sln"
        
      - name: Run dotnet format
        run: dotnet format --verify-no-changes "./Thesis.sln"

      - name: Check for uncommitted changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "There are uncommitted changes after formatting."
            git diff
            exit 1
          fi
