name: Remove old artifacts

on:
  push:
    branches:
      - main
  schedule:
    # Every day at 1am
    - cron: '0 1 * * *'

permissions: write-all

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step to list all artifacts
    - name: List artifacts
      id: list_artifacts
      run: |
        echo "::set-output name=artifacts::$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        https://api.github.com/repos/${{ github.repository }}/actions/artifacts | jq -r '.artifacts[].id')"

    # Step to delete each artifact
    - name: Delete artifacts
      run: |
        for artifact_id in ${{ steps.list_artifacts.outputs.artifacts }}; do
          curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$artifact_id
        done
